### ISSUE TITLE
2.0.1四星圣遗物扫描问题依旧存在

### ISSUE THREAD

**Issue by fatinghenji** [daydreaming666/GenshinArtScanner#2]
- 使用版本：2.0.1
- 升级方法：2.0.1压缩包解压覆盖
- 识别结果截图：
![image](https://user-images.githubusercontent.com/37131177/129846170-0e8669f1-a5ee-46a8-8267-84996526d3ce.png)
- 识别错误文件打包:
  - ![image](https://user-images.githubusercontent.com/37131177/129846815-0c027ce7-16ce-4c69-aa64-f93de274b3df.png)
~不知道为啥穿不上来，我发在discord里面~
  - ![image](https://user-images.githubusercontent.com/37131177/129846903-7fbeae6c-2432-40e1-badd-153ec12c8384.png)
discord也发不了

**Comment by aestilog** [comment]
ArtScannerUI.zip 错误的上传了旧版本的文件，现已修正。十分感谢！
