### ISSUE TITLE
Can't upload .json file to Genshin Optimizer

### ISSUE THREAD

**Issue by ComplexPlatform** [daydreaming666/GenshinArtScanner#4]
Whenever I upload the .json file the tool generates to Genshin Optimizer, I get this error:
>Invalid JSON: TypeError: can't convert undefined to object

Perhaps the GO dev changed the format.

**Comment by synapse73** [comment]
try this fork if you want to import now. https://dualie.ink/genshin-optimizer/#/setting

GO is still working on the importer for this scanner. will be available on GO when genshin 2.1 release

**Comment by ComplexPlatform** [comment]
> 
> 
> try this fork if you want to import now. https://dualie.ink/genshin-optimizer/#/setting

~~It recognizes the number of artifacts but when I click the Import button I get this error:~~

>~~TypeError: m[n] is undefined~~

I rescanned my artifacts and it works fine now.

>GO is still working on the importer for this scanner. will be available on GO when genshin 2.1 release

Glad to hear that. This tool makes adding artifacts to GO much faster. I guess I'll wait for now. Thanks!
